### ISSUE TITLE
10updocker postinstall --silent fails

### ISSUE THREAD

**Issue by gebeer** [10up/wp-local-docker-v2#176]
**Describe the bug**
When installing v2.8 on arch linux with nvm and node v12.20.1 the 10updocker postinstall --silent fails with 
`Error : Command failed: /home/gbr/.nvm/versions/node/v12.20.1/lib/node_modules/wp-local-docker/node_modules/mkcert-prebuilt/1.2.0.bin -install`

Some pointers:
```
Using the local CA at "/home/gbr/.local/share/mkcert" ✨
ERROR: failed to execute "certutil -A": exit status 255

certutil: function failed: SEC_ERROR_LEGACY_DATABASE: The certificate/key database is in an old, unsupported format.
```
An older version (2.7.0) of 10updocker was installing and running fine on node v10.0.0. Today I decided to update and got this error. Same happens on node stable v14.15.3.

**Steps to Reproduce**
1. switch node version to 12.20.1 with `nvm install 12.20.1`
2. run `npm install -g wp-local-docker`
3. Error appears

**Expected behavior**
installation finishes without errors
 - Device: Acer Aspire 7
 - OS: Arch Linux

**Additional context**
I tried to find solutions for `certutil: function failed: SEC_ERROR_LEGACY_DATABASE: The certificate/key database is in an old, unsupported format.` to no avail. 

EDIT: Until this is resoved, I downgraded to v2.7.0 on node 10.0.0 to be able to use this great tool

**Comment by nicoladj77** [comment]
Same issue on Windows 10

> warning "expo-cli > @expo/xdl > @expo/webpack-config > @expo/webpack-pwa-manifest-plugin > @expo/image-utils@0.2.12" has unmet peer dependency "sharp-cli@^1.10.0".
> [4/4] Building fresh packages...
> [-/3] ⢀ waiting...
> [3/3] ⢀ wp-local-docker
> error C:\Users\nicol\AppData\Local\Yarn\Data\global\node_modules\wp-local-docker: Command failed.
> Exit code: 1
> Command: npm run 10updocker postinstall --silent
> Arguments:
> Directory: C:\Users\nicol\AppData\Local\Yarn\Data\global\node_modules\wp-local-docker
> Output:
> '.' is not recognized as an internal or external command,
> 12:11

v 2.7.0 working correctly

**Comment by gebeer** [comment]
> Same issue on Windows 10

Looking at your error output, itis actually not the same issue. Please open new issue. Thanks.

**Comment by eugene-manuilov** [comment]
@gebeer @nicoladj77 thanks for reporting your issues. Could you please try to install `@issue176` version using the following command? 

```sh-session
npm i -g wp-local-docker@issue176
```
It should solve the installation issue, but it won't fix the issue with certutil itself... Please, let me know how it works on your end.

**Comment by eugene-manuilov** [comment]
@dustinrue do you know how to fix the certutil issue in the description?

**Comment by nicoladj77** [comment]
@eugene-manuilov so I tried and the issue persists

> [3/4] Linking dependencies...
> warning "expo-cli > @expo/xdl > @expo/webpack-config > @expo/webpack-pwa-manifest-plugin > @expo/image-utils@0.2.12" has unmet peer dependency "sharp-cli@^1.10.0".
> [4/4] Building fresh packages...
> [3/3] ⠈ wp-local-docker
> [-/3] ⠁ waiting...
> error C:\Users\nicol\AppData\Local\Yarn\Data\global\node_modules\wp-local-docker: Command failed.
> Exit code: 1
> Command: npm run 10updocker postinstall --silent
> Arguments:
> Directory: C:\Users\nicol\AppData\Local\Yarn\Data\global\node_modules\wp-local-docker
> Output:
> '.' is not recognized as an internal or external command,

The difference is that this time the 10updocker command is installed and looks like it's working, while previously the command wasn't installed at all.

**Comment by eugene-manuilov** [comment]
Thanks, @nicoladj77. That's expected behavior for now. The postinstall script tries to install a new local CA root certificate to let you use self-signed certificates for your local sites. But looks like it can't do it. I'll need to figure out why it can't do it.

**Comment by gebeer** [comment]
> Thanks, @nicoladj77. That's expected behavior for now. The postinstall script tries to install a new local CA root certificate to let you use self-signed certificates for your local sites. But looks like it can't do it. I'll need to figure out why it can't do it.

I guess it is a permission issue and may need sudo. Maybe you could do a check for already existing local CA and proceed accordingly?

**Comment by tomalec** [comment]
I'm not sure whether it's the same issue or slightly different one for me.
It fails on Ubuntu 20.04, with Node `12.21.0`. It complains about Docker not running, even though it is actually running:

```
[nodegit] Completed installation successfully.

> nodegit@0.27.0 postinstall /home/tomalec/.nvm/versions/node/v12.21.0/lib/node_modules/wp-local-docker/node_modules/nodegit
> node lifecycleScripts/postinstall


> wp-local-docker@2.8.1 postinstall /home/tomalec/.nvm/versions/node/v12.21.0/lib/node_modules/wp-local-docker
> npm run 10updocker postinstall --silent


 Error : Docker is not running...

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-local-docker@2.8.1 postinstall: `npm run 10updocker postinstall --silent`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wp-local-docker@2.8.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tomalec/.npm/_logs/2021-02-28T19_51_36_580Z-debug.log
```

```
$ ps -ef | grep docker 
root       46357       1  0 20:38 ?        00:00:00 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

```

**Comment by tomalec** [comment]
I managed to solve my problem with https://developer.wordpress.org/block-editor/tutorials/devenv/docker-ubuntu/
```
# /etc/systemd/system/docker.service.d
[Service]
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2376
```

**Comment by JanKruft** [comment]
@eugene-manuilov . Really great tool. <3 . One question What was the fix @issue176. The 2.8.1 is working well on my ubuntu . on windows 10 it fails with the "." issue.

**Comment by tylercherpak** [comment]
Hey everyone,

I'm going to close this since I think this is resolved in the latest `3.0.0` release. Please run `npm i -g wp-local-docker` to install the latest version. 

Please feel free to reopen this ticket if you are still experiencing this issue. Thanks! 😄

**Comment by tomalec** [comment]
@tylercherpak Could you reopen it?
I still experience this, with a fresh install :
```
 tomalec  ~  docker --version
Docker version 20.10.13, build a224086
 tomalec  ~  docker compose version
Docker Compose version v2.12.0
 tomalec  ~  ps -ef | grep docker 
root       23602       1  0 14:35 ?        00:00:01 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
```

```
 tomalec  ~  npm install -g wp-local-docker
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/tomalec/.nvm/versions/node/v16.18.0/lib/node_modules/wp-local-docker
npm ERR! command failed
npm ERR! command sh -c -- npm run 10updocker postinstall --silent
npm ERR! Successfully Configured WP Local Docker!
npm ERR! Error : Docker is not running...

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tomalec/.npm/_logs/2022-10-21T12_50_06_729Z-debug-0.log

```

**Comment by tylercherpak** [comment]
@tomalec it looks like the error you are getting is because docker desktop isn't running.
`npm ERR! Error : Docker is not running...`
Hope this helps!

**Comment by tomalec** [comment]
@tylercherpak Docker is and was running.

When I did
```
npm install -g wp-local-docker --ignore-scripts
10updocker configure
10updocker create
```
everything worked.

So it seems `postinstall` fails to find the docker for some reason. Then once installed, 10updocker finds it without a problem.
