### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries - M1 MAC

### ISSUE THREAD

**Issue by Raandino** [10up/wp-local-docker-v2#247]
**Describe your question**

I'm changing to m1 mac from linux, I was able to install 10updocker , docker, node etc, problem is when trying to create a new enviroment gives me this error, "**no matching manifest for linux/arm64/v8 in the manifest list entries**" how can I fix it? I have been trying nonstop even changing the .yaml file but nothing seems to work.

https://user-images.githubusercontent.com/48781148/137781262-3f661a6b-bbd0-440f-8843-dd11198dfb2a.mov

**Comment by tylercherpak** [comment]
Hey y'all 👋 

This should be resolved now in the latest `3.0.0` release.

Let us know if you still running into issues.

Thanks!

**Comment by Raandino** [comment]
Hey! @tylercherpak  I just update **10-up-docker** but I still encounter  the issue, 
![image](https://user-images.githubusercontent.com/48781148/141856035-3df7f5eb-8177-43e3-bcf9-2c6964a62a8d.png)

**Comment by tylercherpak** [comment]
@Raandino can you take a back up of the `~/.wplocaldocker/global/docker-compose.yml` and then run `10updocker configure` this should replace the `docker-compose.yml` file and replace mysql to mariadb (which has ARM support).

**Comment by Raandino** [comment]
@tylercherpak , now is working, I did a fresh install and delete old files, now works as intended @rebeccahum  you should try as well.
![image](https://user-images.githubusercontent.com/48781148/141861299-e6930c6c-0152-4e2b-8a6c-9bd2df2ef882.png)
